-- Журнал перелива событий в прод-БД (crmdb).
--
-- Событие, заведённое формой или материализованное из цепочки, ложится в НАШ слой B —
-- локальные копии прод-таблиц. Боевые движки читают не их, а те же таблицы в crmdb,
-- поэтому нужен перенос. Здесь записывается, что и во что уехало.
--
-- Почему не хватило flow.t_materialization: он отвечает на вопрос «из чего сделана эта
-- строка НАШЕГО слоя B» (наша цепочка/событие -> наша таблица+id). Здесь вопрос другой —
-- «куда эта наша строка уехала в проде» (наша таблица+id -> id в crmdb). Смешивать их в
-- одной таблице значило бы, что колонка prod_id означает то одно, то другое.
CREATE TABLE IF NOT EXISTS flow.t_event_export (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    bigint NOT NULL REFERENCES flow.d_event (id) ON DELETE CASCADE,
    our_table   varchar(128) NOT NULL,
    our_id      bigint NOT NULL,
    prod_id     bigint NOT NULL,
    exported_at timestamptz NOT NULL DEFAULT now(),
    exported_by varchar(255),
    -- Идемпотентность: строка, однажды уехавшая в прод, второй раз не уедет. Без этого
    -- повторное нажатие «Перелить» плодило бы дубли — ровно то, на чём мы уже обожглись
    -- с очередью шаблонов (см. ProdSyncService).
    CONSTRAINT t_event_export_row_uq UNIQUE (our_table, our_id)
);

CREATE INDEX IF NOT EXISTS t_event_export_event_idx ON flow.t_event_export (event_id);

COMMENT ON TABLE flow.t_event_export IS
    'Что из нашего слоя B уехало в прод-БД и под какими id. Пишет EventExportService.';
