-- Лог действий админки над шаблонами (заведение/правка/удаление).
-- Структура 1:1 по прод-спецификации t_admin_log:
--   id bigint NOT NULL, table_name varchar, operation varchar,
--   old_row jsonb, action_user varchar, timestamp_cr timestamp NOT NULL.
-- Физическое имя таблицы конфигурируется (ADMIN_LOG_TABLE), по умолчанию arch.t_admin_log.
CREATE TABLE IF NOT EXISTS arch.t_admin_log (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name   character varying,
    operation    character varying,
    old_row      jsonb,
    action_user  character varying,
    timestamp_cr timestamp without time zone NOT NULL DEFAULT now()
);
