-- ============================================================================
-- СЛОЙ B: копии продовых таблиц процесса коммуникаций (1:1 по DDL из прода).
-- Наша админка материализует сюда конфигурацию (как старая Appsmith-админка
-- DO-скриптом), существующие движки прода читают эти же структуры.
-- Отличие от прода: id везде GENERATED BY DEFAULT AS IDENTITY (никаких max+1).
-- ============================================================================
CREATE SCHEMA IF NOT EXISTS tracker;
CREATE SCHEMA IF NOT EXISTS scheduler;
CREATE SCHEMA IF NOT EXISTS template;
CREATE SCHEMA IF NOT EXISTS commapi;

-- ---------------------------------------------------------------- ОНЛАЙН ----

-- Справочник параметров создания коммуникации (на него ссылается t_event_comm)
CREATE TABLE IF NOT EXISTS tracker.d_comm_creation (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allow_ml              boolean NOT NULL DEFAULT false,
    send_delay            integer,
    lifetime              integer,
    comm_decision_tree_id bigint,
    notify_channel        varchar(10),
    timestamp_cr          timestamp NOT NULL DEFAULT now(),
    check_interval        interval
);

-- Справочник онлайн-событий
CREATE TABLE IF NOT EXISTS tracker.t_event_comm (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name       varchar(255) NOT NULL,
    system           varchar(255),
    id_comm_creation bigint NOT NULL REFERENCES tracker.d_comm_creation (id),
    is_active        boolean NOT NULL DEFAULT false,
    timestamp_cr     timestamp NOT NULL DEFAULT now(),
    sub_channel      varchar(255),
    platform         varchar(50),
    group_event_descr varchar(255),
    stop_product_ids bigint[],
    stop_events      jsonb,
    is_chain         boolean NOT NULL DEFAULT false
);

-- ------------------------------------------------------------ РАСПИСАНИЕ ----

-- Справочник событий расписания (+ сорс шаблона + канал)
CREATE TABLE IF NOT EXISTS scheduler.t_get_event (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection             varchar(255) NOT NULL,
    event_name            varchar(255),
    system                varchar(255),
    send_delay            integer,
    product_id            bigint,
    is_deferred           boolean NOT NULL,
    source                varchar(255),
    allow_ml              boolean NOT NULL,
    notify_channel        varchar(20),
    comm_decision_tree_id bigint,
    params                jsonb,
    is_active             boolean NOT NULL,
    life_time             integer,
    sub_channel           varchar(255),
    platform              varchar(50),
    group_event_descr     varchar(255)
);

-- Настройки запуска события
CREATE TABLE IF NOT EXISTS scheduler.t_launch_settings (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection          varchar(255) NOT NULL,
    time_start         timestamp NOT NULL,
    period_unit        varchar(6),
    period_q           integer,
    database           varchar(255) NOT NULL,
    description        varchar(255),
    is_active          boolean NOT NULL,
    status             varchar(255) NOT NULL,
    date_start         timestamp,
    date_end           timestamp,
    date_next          timestamp,
    is_batch           boolean NOT NULL,
    max_retry_attempts integer DEFAULT 1,
    crontab            varchar,
    last_exec_status   varchar(255),
    cron_status        varchar(255),
    job_group          varchar(255) DEFAULT 'CRM',
    priority           integer,
    timestamp_cr       timestamp,
    timestamp_upd      timestamp
);

-- Шаги события (SQL-код формирования выборки)
CREATE TABLE IF NOT EXISTS scheduler.t_execution_steps (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    t_launch_settings_id bigint NOT NULL REFERENCES scheduler.t_launch_settings (id),
    process_name         varchar(255) NOT NULL,
    order_num            integer NOT NULL,
    is_active            boolean NOT NULL,
    returns_result_set   boolean NOT NULL,
    last_ds              timestamp,
    last_de              timestamp,
    sql_text             varchar,
    last_err             varchar,
    status               varchar(255),
    retry_count          integer
);

-- ------------------------------------------------------------- МАППИНГИ ----

-- Событие → шаблон
CREATE TABLE IF NOT EXISTS template.d_template_mapping (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    get_event_id       bigint,
    event_name         varchar(255),
    system             varchar(255),
    segment_id         integer,
    notify_channel     varchar(10),
    template_id        integer,
    is_multiple_choice boolean DEFAULT false
);

-- Событие → шаблоны цепочки (создана пользователем для прозрачности цепочек)
CREATE TABLE IF NOT EXISTS template.d_template_mapping_mass (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    bigint,
    event_name  varchar,
    template_id integer,
    channel     varchar
);

-- Событие → метод отправки
CREATE TABLE IF NOT EXISTS commapi.d_definition_mapping (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    get_event_id            bigint,
    event_name              varchar(255),
    system                  varchar(255),
    notify_channel          varchar(10),
    definition_key          varchar(255) NOT NULL,
    business_key_prefix     varchar(255) NOT NULL,
    is_correlation          boolean NOT NULL DEFAULT false,
    correlation_keys        text[],
    notify_channel_priority jsonb
);

-- ------------------------------------------------- ПЕРЕМЕННЫЕ И ССЫЛКИ ----
-- Структура восстановлена по DO-скрипту старой админки (точного DDL нет).

CREATE TABLE IF NOT EXISTS template.d_variables (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(255) NOT NULL,
    is_pd          boolean NOT NULL DEFAULT false,
    is_application boolean NOT NULL DEFAULT false,
    is_link        boolean NOT NULL DEFAULT false,
    is_service     boolean NOT NULL DEFAULT false,
    is_logo        boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS template.d_variable_synonyms (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    synonym        varchar(255),
    notify_channel varchar(20),
    system         varchar(255),
    variable_id    integer REFERENCES template.d_variables (id)
);

CREATE TABLE IF NOT EXISTS template.d_variables_link (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variable_id     integer REFERENCES template.d_variables (id),
    page_link       varchar,
    link_parameters varchar
);
