-- ============================================================================
-- ПАНЕЛЬ ОТКЛОНЕНИЙ: выручка по дням, найденные отклонения и работа с ними.
--
-- До сих пор раздел жил целиком в браузере: цифры приезжали из Excel, а
-- комментарии и статусы гипотез лежали в localStorage. Значит история была
-- только у того, кто последним нажал «Сохранить в Excel», и доказать «это
-- отклонение мы видели и разобрали» было нечем.
--
-- Три слоя, намеренно разделённые:
--   d_* — факт (выручка) и настройки, живут независимо от расчётов;
--   t_run* — СНИМОК расчёта: что именно показывалось в разделе и с какими
--            порогами. Пересчёт не переписывает старые снимки — в этом и смысл;
--   t_note — ручной слой: комментарий и статус гипотезы, переживает пересчёты.
--
-- Конвенция имён общая с flow: d_* — данные/конфиг, t_* — то, что копится.
-- ============================================================================
CREATE SCHEMA IF NOT EXISTS deviation;

-- ---------------------------------------------------------------------------
-- Откуда пришли цифры. Сейчас это загрузка файла из раздела, позже — регулярная
-- подтяжка из источника; журнал один на оба случая, чтобы при подключении ETL
-- не заводить вторую историю поступлений.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS deviation.t_load (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          varchar(16) NOT NULL CHECK (kind IN ('file', 'etl')),
    mode          varchar(16) NOT NULL DEFAULT 'append' CHECK (mode IN ('replace', 'append')),
    file_name     varchar(512),
    date_from     date,
    date_to       date,
    rows_total    integer NOT NULL DEFAULT 0,
    rows_new      integer NOT NULL DEFAULT 0,
    rows_updated  integer NOT NULL DEFAULT 0,
    status        varchar(16) NOT NULL DEFAULT 'ok' CHECK (status IN ('ok', 'error')),
    message       text,
    timestamp_cr  timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz,
    created_by    varchar(255)
);

-- ---------------------------------------------------------------------------
-- Факт: выручка за день в разрезе продукта и канала — та самая плоская таблица
-- «Данные_день_продукт» из файла. Всё остальное в разделе (база-медиана,
-- отклонения, тренды, помесячная сводка) считается из неё.
--
-- Уникальность по четвёрке обязательна: дозагрузка того же дня должна обновлять
-- строку, а не добавлять вторую. Без неё повторный импорт одного файла удвоил
-- бы выручку и нарисовал бы всплеск на ровном месте.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS deviation.d_revenue_daily (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fact_date     date NOT NULL,
    group1        varchar(255) NOT NULL,      -- направление: Кредиты, Страхование, Бизнес…
    group2        varchar(255) NOT NULL,      -- продукт: Микрозаймы, ОСАГО, РКО…
    channel       varchar(64)  NOT NULL,      -- Group3: sms, email, callcenter, mobile-push…
    revenue       numeric(18, 2) NOT NULL,
    load_id       bigint REFERENCES deviation.t_load (id) ON DELETE SET NULL,
    timestamp_cr  timestamptz NOT NULL DEFAULT now(),
    timestamp_upd timestamptz,
    CONSTRAINT uq_revenue_daily UNIQUE (fact_date, group1, group2, channel)
);
CREATE INDEX IF NOT EXISTS ix_revenue_daily_date ON deviation.d_revenue_daily (fact_date);

-- ---------------------------------------------------------------------------
-- Пороги, по которым день считается отклонением, а тренд — снижением. Раньше
-- они были зашиты в JS и продублированы в подписи под разделом; правка означала
-- выкладку. Строка одна: это настройка инструмента, а не справочник.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS deviation.d_threshold (
    id                  smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    base_window         smallint NOT NULL DEFAULT 7,       -- окно скользящей медианы, дней
    spike_pct           numeric(5, 2) NOT NULL DEFAULT 20, -- |откл| итога, %
    product_spike_pct   numeric(5, 2) NOT NULL DEFAULT 60, -- |откл| по продукту, %
    decline_min_days    smallint NOT NULL DEFAULT 14,      -- длительность плавного снижения
    decline_total_pct   numeric(5, 2) NOT NULL DEFAULT 20, -- глубина снижения итога, %
    decline_product_pct numeric(5, 2) NOT NULL DEFAULT 30, -- глубина снижения продукта, %
    timestamp_upd       timestamptz NOT NULL DEFAULT now(),
    updated_by          varchar(255)
);
INSERT INTO deviation.d_threshold (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Снимок расчёта. Пороги пишутся В САМ снимок, а не берутся из d_threshold при
-- чтении: пороги меняются, и через полгода иначе не объяснить, почему день
-- попал в отклонения, — а именно это и требуется доказывать.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS deviation.t_run (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calc_ts             timestamptz NOT NULL DEFAULT now(),
    date_from           date NOT NULL,
    date_to             date NOT NULL,
    days_count          integer NOT NULL DEFAULT 0,
    flags_count         integer NOT NULL DEFAULT 0,
    declines_count      integer NOT NULL DEFAULT 0,
    checkdays_count     integer NOT NULL DEFAULT 0,
    products_count      integer,
    total_revenue       numeric(20, 2),
    base_window         smallint NOT NULL,
    spike_pct           numeric(5, 2) NOT NULL,
    product_spike_pct   numeric(5, 2) NOT NULL,
    decline_min_days    smallint NOT NULL,
    decline_total_pct   numeric(5, 2) NOT NULL,
    decline_product_pct numeric(5, 2) NOT NULL,
    load_id             bigint REFERENCES deviation.t_load (id) ON DELETE SET NULL,
    created_by          varchar(255)
);
CREATE INDEX IF NOT EXISTS ix_run_calc_ts ON deviation.t_run (calc_ts DESC);

-- Ряд «факт против нормы» — лист «Ежедневно_итого».
CREATE TABLE IF NOT EXISTS deviation.t_run_daily (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        bigint NOT NULL REFERENCES deviation.t_run (id) ON DELETE CASCADE,
    fact_date     date NOT NULL,
    revenue       numeric(18, 2) NOT NULL,
    base_median   numeric(18, 2),
    deviation_pct numeric(7, 2),
    dod_pct       numeric(7, 2),
    is_flagged    boolean NOT NULL DEFAULT false,
    UNIQUE (run_id, fact_date)
);

-- Дни-отклонения — лист «Дни_отклонений». drivers: топ продуктов, вытянувших день.
CREATE TABLE IF NOT EXISTS deviation.t_run_flag (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          bigint NOT NULL REFERENCES deviation.t_run (id) ON DELETE CASCADE,
    fact_date       date NOT NULL,
    direction       varchar(16) NOT NULL CHECK (direction IN ('up', 'down')),
    deviation_pct   numeric(7, 2) NOT NULL,
    revenue         numeric(18, 2),
    base_median     numeric(18, 2),
    strength        varchar(16),                -- сильное / среднее
    label           varchar(16),                -- confident (гипотеза ясна) / check (нужна проверка)
    hypothesis_auto text,
    drivers         jsonb,
    UNIQUE (run_id, fact_date)
);

-- Плавные снижения — лист «Плавные_снижения».
CREATE TABLE IF NOT EXISTS deviation.t_run_decline (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          bigint NOT NULL REFERENCES deviation.t_run (id) ON DELETE CASCADE,
    level_kind      varchar(16) NOT NULL CHECK (level_kind IN ('total', 'product')),
    level_name      varchar(512) NOT NULL,      -- «Итого по всем продуктам» или «Кредиты / Микрозаймы / email»
    date_start      date NOT NULL,
    date_end        date NOT NULL,
    days_count      integer NOT NULL,
    revenue_start   numeric(18, 2),
    revenue_end     numeric(18, 2),
    drop_pct        numeric(7, 2) NOT NULL,
    hypothesis_auto text,
    UNIQUE (run_id, level_name, date_start)
);

-- Помесячная сводка — лист «Помесячно».
CREATE TABLE IF NOT EXISTS deviation.t_run_monthly (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        bigint NOT NULL REFERENCES deviation.t_run (id) ON DELETE CASCADE,
    month_start   date NOT NULL,               -- первое число месяца
    total_revenue numeric(20, 2) NOT NULL,
    avg_day       numeric(18, 2),
    min_day       numeric(18, 2),
    max_day       numeric(18, 2),
    std_dev       numeric(18, 2),
    mom_pct       numeric(7, 2),               -- NULL у первого месяца периода
    UNIQUE (run_id, month_start)
);

-- «Требуют точечной проверки»: кластер аномалий без однозначной причины.
CREATE TABLE IF NOT EXISTS deviation.t_run_checkday (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id    bigint NOT NULL REFERENCES deviation.t_run (id) ON DELETE CASCADE,
    fact_date date NOT NULL,
    note_auto text,
    UNIQUE (run_id, fact_date)
);

-- ---------------------------------------------------------------------------
-- Ручной слой: комментарий и решение по гипотезе. Живёт ВНЕ снимков — иначе
-- пересчёт обнулял бы разбор, ради которого раздел и нужен.
--
-- object_key — бизнес-ключ объекта: для дня это дата, для тренда «уровень|дата
-- начала». Тренд после дозагрузки дней может сдвинуть границу, и комментарий
-- окажется без пары; поэтому рядом лежит snapshot — уровень, период и глубина
-- на момент написания. По нему такую запись можно узнать и перепривязать
-- руками, а не гадать, к чему относился текст.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS deviation.t_note (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_kind   varchar(16) NOT NULL CHECK (object_kind IN ('day', 'decline')),
    object_key    varchar(512) NOT NULL,
    fact_date     date,                        -- день или начало тренда — чтобы искать по датам
    level_name    varchar(512),                -- уровень тренда
    comment       text,
    status        varchar(16) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'solved')),
    snapshot      jsonb,
    timestamp_cr  timestamptz NOT NULL DEFAULT now(),
    created_by    varchar(255),
    timestamp_upd timestamptz,
    updated_by    varchar(255),
    CONSTRAINT uq_note_object UNIQUE (object_kind, object_key)
);
CREATE INDEX IF NOT EXISTS ix_note_date ON deviation.t_note (fact_date);
