-- ============================================================================
-- КАНАЛЫ: сколько канал стоит и что о нём говорят почтовые постмастеры.
--
-- Раздел отвечает на два вопроса: во что обходится одна коммуникация в канале
-- и в каком состоянии канал находится (пока — только для почты, по данным
-- Google и Mail.ru Postmaster).
--
-- Затраты и объём хранятся СТРОКАМИ С ПЕРИОДОМ, а не одним числом на канал:
-- договоры меняются, объёмы тоже, и цена «сейчас» без истории не строится —
-- при смене объёма прошлые месяцы пересчитались бы задним числом.
-- ============================================================================
CREATE SCHEMA IF NOT EXISTS channel;

-- ---------------------------------------------------------------------------
-- Каналы. Список закрытый и совпадает с каналами шаблонов; заводится здесь, а
-- не в коде, потому что рядом лежит настройка «бесплатный» и подписи, которые
-- правятся без выкладки.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channel.d_channel (
    id            varchar(32) PRIMARY KEY,       -- cc | sms | email | push | vk | fa
    label         varchar(64) NOT NULL,
    sort_order    smallint NOT NULL DEFAULT 100,
    /* Канал бесплатный: тарификация не ведётся, цена коммуникации — ноль.
       Введённые строки затрат при этом НЕ удаляются: галку снимут — всё
       вернётся на место. */
    is_free       boolean NOT NULL DEFAULT false,
    is_active     boolean NOT NULL DEFAULT true,
    timestamp_upd timestamptz,
    updated_by    varchar(255)
);

INSERT INTO channel.d_channel (id, label, sort_order) VALUES
    ('cc',    'Callcenter',   10),
    ('sms',   'SMS',          20),
    ('email', 'E-mail',       30),
    ('push',  'Mobile-push',  40),
    ('vk',    'ВК',           50),
    ('fa',    'Финпомощник',  60)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Статьи затрат: строка на каждое, за что платим в канале.
-- amount_period — период самой суммы (в месяц / в год), date_from..date_to —
-- срок, за который платим. Разделять обязательно: годовая сумма за полугодовой
-- договор и месячная за тот же срок — разные деньги.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channel.d_cost (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id    varchar(32) NOT NULL REFERENCES channel.d_channel (id) ON DELETE CASCADE,
    amount        numeric(18, 2) NOT NULL DEFAULT 0,
    amount_period varchar(8) NOT NULL DEFAULT 'year' CHECK (amount_period IN ('month', 'year')),
    date_from     date,
    date_to       date,
    vendor        varchar(255),
    note          text,
    timestamp_cr  timestamptz NOT NULL DEFAULT now(),
    created_by    varchar(255),
    timestamp_upd timestamptz,
    updated_by    varchar(255)
);
CREATE INDEX IF NOT EXISTS ix_cost_channel ON channel.d_cost (channel_id, date_from);

-- ---------------------------------------------------------------------------
-- Модель тарификации. Сейчас у всех каналов она одна — поштучные отправки
-- (kind = per_message), но поле оставлено: у колл-центра это будут минуты или
-- звонки, и тогда добавится вид, а не вторая таблица.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channel.d_volume (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id    varchar(32) NOT NULL REFERENCES channel.d_channel (id) ON DELETE CASCADE,
    kind          varchar(16) NOT NULL DEFAULT 'per_message',
    volume        numeric(18, 2) NOT NULL DEFAULT 0,
    volume_period varchar(8) NOT NULL DEFAULT 'year' CHECK (volume_period IN ('month', 'year')),
    date_from     date,
    date_to       date,
    note          text,
    timestamp_cr  timestamptz NOT NULL DEFAULT now(),
    created_by    varchar(255),
    timestamp_upd timestamptz,
    updated_by    varchar(255)
);
CREATE INDEX IF NOT EXISTS ix_volume_channel ON channel.d_volume (channel_id, date_from);

-- ---------------------------------------------------------------------------
-- Метрики постмастеров по дням. Обе системы отдают ограниченное окно (Google —
-- около 90 дней), поэтому копим у себя: без этого история пропадает, а
-- сравнивать «стало хуже или лучше» приходится по памяти.
--
-- Ключевые показатели вынесены в колонки, полный ответ лежит в raw: состав
-- полей у постмастеров меняется, и терять то, что сегодня не показываем, не
-- хочется.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channel.t_postmaster_daily (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source            varchar(16) NOT NULL CHECK (source IN ('google', 'mailru')),
    domain            varchar(255) NOT NULL,
    stat_date         date NOT NULL,
    sent              bigint,          -- отправлено (Mail.ru)
    delivered         bigint,          -- доставлено (Mail.ru)
    read_count        bigint,          -- прочитано (Mail.ru)
    complaints        bigint,          -- жалобы (Mail.ru)
    spam_rate         numeric(9, 6),   -- доля спам-жалоб: Google userReportedSpamRatio, Mail.ru spam_percent
    domain_reputation varchar(32),     -- Google: HIGH | MEDIUM | LOW | BAD, Mail.ru: reputation
    ip_reputation     varchar(32),     -- Google, худшая из категорий за день
    spf_ratio         numeric(9, 6),
    dkim_ratio        numeric(9, 6),
    dmarc_ratio       numeric(9, 6),
    raw               jsonb,
    timestamp_cr      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_postmaster_daily UNIQUE (source, domain, stat_date)
);
CREATE INDEX IF NOT EXISTS ix_postmaster_date ON channel.t_postmaster_daily (stat_date DESC);

-- ---------------------------------------------------------------------------
-- Доступы к постмастерам. Строка одна — как app.jira_connection: панель ходит в
-- один кабинет каждой системы под одной учёткой. Токены наружу не отдаются ни в
-- одном ответе, наверх уходит только признак «заполнено».
--
-- У Google refresh_token меняется на access через свой OAuth, у Mail.ru — через
-- o2.mail.ru с фиксированным client_id postmaster_api_client, поэтому у него
-- хранится только refresh_token.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app.postmaster_connection (
    id                    bigint PRIMARY KEY DEFAULT 1,
    domain                varchar(255) NOT NULL DEFAULT 'email.banki.ru',
    google_client_id      text,
    google_client_secret  text,
    google_refresh_token  text,
    /* v1 (trafficStats) или v2 (domainStats.query). v2 умеет диапазон дат и
       статус SPF/DKIM/DMARC, но доступен не всем кабинетам — версия выбирается
       настройкой, а не гаданием по ошибке. */
    google_api_version    varchar(4) NOT NULL DEFAULT 'v1' CHECK (google_api_version IN ('v1', 'v2')),
    mailru_refresh_token  text,

    google_status         varchar(20),
    google_error          text,
    google_checked_at     timestamptz,
    mailru_status         varchar(20),
    mailru_error          text,
    mailru_checked_at     timestamptz,

    timestamp_upd         timestamptz NOT NULL DEFAULT now(),
    updated_by            varchar(255),
    CONSTRAINT chk_postmaster_single_row CHECK (id = 1)
);
INSERT INTO app.postmaster_connection (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
