-- ============================================================================
-- СЛОЙ A: нормализованная модель процесса коммуникаций (наша, «истина» для UI
-- и Flow Builder). Материализуется в слой B (tracker/scheduler/template/commapi)
-- сервисом MaterializationService. Конвенция имён: d_* — конфиг, t_* — runtime.
-- ============================================================================
CREATE SCHEMA IF NOT EXISTS flow;

-- Единый справочник событий (вместо tracker.t_event_comm + scheduler.t_get_event)
CREATE TABLE IF NOT EXISTS flow.d_event (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind              varchar(10) NOT NULL CHECK (kind IN ('income', 'time')),
    event_name        varchar(255) NOT NULL,
    system            varchar(255),
    source            varchar(255),
    group_event_descr varchar(255),
    description       varchar(255),
    journey_id        varchar(36) REFERENCES app.journeys (id) ON DELETE SET NULL,
    is_active         boolean NOT NULL DEFAULT true,
    timestamp_cr      timestamptz NOT NULL DEFAULT now(),
    timestamp_upd     timestamptz,
    UNIQUE (event_name, system)
);

-- Событие → настройки доставки
CREATE TABLE IF NOT EXISTS flow.d_event_delivery (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                bigint NOT NULL REFERENCES flow.d_event (id) ON DELETE CASCADE,
    notify_channel          varchar(20),
    sub_channel             varchar(255),
    platform                varchar(50),
    send_delay              integer,
    life_time               integer,
    check_interval          interval,
    allow_ml                boolean NOT NULL DEFAULT false,
    comm_decision_tree_id   bigint,
    stop_product_ids        bigint[],
    stop_events             jsonb,
    notify_channel_priority jsonb
);

-- Событие → расписание (только kind=time), чистый конфиг без runtime
CREATE TABLE IF NOT EXISTS flow.d_event_schedule (
    event_id           bigint PRIMARY KEY REFERENCES flow.d_event (id) ON DELETE CASCADE,
    crontab            varchar,
    time_start         timestamp,
    period_unit        varchar(6),
    period_q           integer,
    date_start         timestamp,
    date_end           timestamp,
    database           varchar(255),
    is_batch           boolean NOT NULL DEFAULT true,
    max_retry_attempts integer DEFAULT 1,
    priority           integer,
    job_group          varchar(255) DEFAULT 'CRM'
);

-- Событие → SQL-шаги выборки (конфиг)
CREATE TABLE IF NOT EXISTS flow.d_event_step (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           bigint NOT NULL REFERENCES flow.d_event (id) ON DELETE CASCADE,
    order_num          integer NOT NULL,
    process_name       varchar(255),
    sql_text           varchar,
    returns_result_set boolean NOT NULL DEFAULT false,
    is_active          boolean NOT NULL DEFAULT true
);

-- История исполнений шагов (runtime отдельно от конфига, ничего не затирается)
CREATE TABLE IF NOT EXISTS flow.t_event_step_run (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id       bigint NOT NULL REFERENCES flow.d_event_step (id) ON DELETE CASCADE,
    started_at    timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz,
    status        varchar(20),
    error         varchar,
    rows_affected bigint
);

-- Событие → шаблон: одиночные (step_no NULL) и цепочки (step_no = позиция/день)
CREATE TABLE IF NOT EXISTS flow.d_event_template (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           bigint NOT NULL REFERENCES flow.d_event (id) ON DELETE CASCADE,
    template_id        bigint,           -- FK на template.d_template (задаётся ниже)
    step_no            integer,          -- NULL = одиночный шаблон
    segment_id         integer,
    is_multiple_choice boolean DEFAULT false
);

-- Событие → метод отправки
CREATE TABLE IF NOT EXISTS flow.d_event_definition (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                bigint NOT NULL REFERENCES flow.d_event (id) ON DELETE CASCADE,
    notify_channel          varchar(20),
    definition_key          varchar(255),
    business_key_prefix     varchar(255),
    is_correlation          boolean NOT NULL DEFAULT false,
    correlation_keys        text[],
    notify_channel_priority jsonb
);

-- Журнал соответствий слоёв: что и во что материализовалось в слое B
CREATE TABLE IF NOT EXISTS flow.t_materialization (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    our_entity      varchar(64)  NOT NULL,   -- напр. 'flow.d_event' / 'app.journeys'
    our_id          varchar(64)  NOT NULL,
    prod_table      varchar(128) NOT NULL,   -- напр. 'scheduler.t_get_event'
    prod_id         varchar(64)  NOT NULL,
    materialized_at timestamptz  NOT NULL DEFAULT now(),
    materialized_by varchar(255)
);

-- ------------------------- Единый справочник шаблонов (свёртка четырёх) ----

-- Ядро — общие колонки типизированы; канальные поля — в channel_props jsonb:
--   sms:   msg_text, sender_name, antispam_check, brief, name
--   push:  title, msg_text, deep_link, webview_url, img_ios, img_android, time_to_live, brief, name
--   email: letteros_id, subject, email_from, preheader, is_service, is_info, utm_custom, trigger_code
--   cc:    segment, source_system, host_id, ml_check_probability, ml_probability_required,
--          cutpercent, nocutpercent, placement, kvint_campaign_id
CREATE TABLE IF NOT EXISTS template.d_template (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel                     varchar(10) NOT NULL CHECK (channel IN ('sms', 'push', 'email', 'cc')),
    code                        bigint NOT NULL,
    communication_name          varchar(255),
    campaign_name               varchar(255),
    communication_type          varchar(16),
    business_communication_type varchar(16),
    trigger_type                varchar(8),
    sending_day                 smallint,
    product_type                text[],
    partner_name                varchar(255),
    touch_point                 varchar(255),
    aff_sub3                    varchar(255),
    selection_wizard_service    varchar(16),
    marketplace                 boolean DEFAULT false,
    dialog                      boolean DEFAULT false,
    loyalty                     boolean DEFAULT false,
    national_rating             boolean DEFAULT false,
    news                        boolean DEFAULT false,
    mobile_app                  boolean DEFAULT false,
    night_send                  boolean DEFAULT false,
    permanent_exclude           boolean DEFAULT false,
    active_flag                 boolean NOT NULL DEFAULT true,
    channel_props               jsonb NOT NULL DEFAULT '{}',
    timestamp_cr                timestamptz NOT NULL DEFAULT now(),
    timestamp_upd               timestamptz,
    UNIQUE (channel, code)
);

ALTER TABLE flow.d_event_template
    ADD CONSTRAINT fk_event_template_template
    FOREIGN KEY (template_id) REFERENCES template.d_template (id) ON DELETE SET NULL;

-- Шаблон → переменные
CREATE TABLE IF NOT EXISTS template.d_template_variable (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id bigint  NOT NULL REFERENCES template.d_template (id) ON DELETE CASCADE,
    variable_id integer NOT NULL REFERENCES template.d_variables (id),
    required    boolean NOT NULL DEFAULT false,
    UNIQUE (template_id, variable_id)
);

-- Шаблон → ссылки (переменные с is_link = true; параметры — в d_variables_link)
CREATE TABLE IF NOT EXISTS template.d_template_link (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id bigint  NOT NULL REFERENCES template.d_template (id) ON DELETE CASCADE,
    variable_id integer NOT NULL REFERENCES template.d_variables (id),
    UNIQUE (template_id, variable_id)
);

-- ------------------------------------------------ Цепочки: тип и метка ----
ALTER TABLE app.journeys
    ADD COLUMN IF NOT EXISTS kind varchar(10) NOT NULL DEFAULT 'online'
        CHECK (kind IN ('online', 'offline'));
ALTER TABLE app.journeys
    ADD COLUMN IF NOT EXISTS continues_journey_id varchar(36) REFERENCES app.journeys (id) ON DELETE SET NULL;
