-- Импорт календаря промо (CRM-ПРОМО.xlsx, лист «Календарь») в app.promo_plan.
--
-- 115 строк = 77 промо из файла, где мультиканал («email, push») разложен по нашему
-- правилу «один канал = одна строка». Колонки: дата, продукт, база, канал, тотал,
-- ответственный, статус, комментарий и communication_name (название из файла —
-- партнёра и уникального имени в выгрузке нет, поэтому авто-сборка имени неполная).
--
-- Требует миграции V24 (колонка communication_name) — она применяется при старте
-- приложения, так что сначала раскатывай образ, потом запускай этот скрипт.
--
-- Запуск на сервере:
--   docker exec -i crm-admin-db-prod psql -U crm -d crm < crm-admin/scripts/promo_import.sql
--
-- Скрипт безопасно перезапускать: он сносит только свои прежние строки
-- (created_by='import:CRM-ПРОМО.xlsx'), записи, заведённые людьми, не трогает.
SET client_encoding='UTF8';
BEGIN;
DELETE FROM app.promo_plan WHERE created_by='import:CRM-ПРОМО.xlsx';
INSERT INTO app.promo_plan
 (plan_date, product, partner, base, channel, is_total, uniq_name, task_key, owner_name, status, note, communication_name, created_by, updated_by)
VALUES
(DATE '2026-07-07', 'КК', '', 'КК, ПК', 'push', false, '', '', 'Саша', 'запланировано', '', 'Альфа-Карта', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-08', 'Ипотека', '', 'Вся база Москва+МО', 'email', false, '', '', 'Саша', 'запланировано', '', 'Береговой 8% (премиум ипотека) (гео)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-08', 'Ипотека', '', 'Вся база Москва+МО', 'push', false, '', '', 'Саша', 'запланировано', '', 'Береговой 8% (премиум ипотека) (гео)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-08', 'РКО', '', 'Бизнес', 'email', false, '', '', 'Юля', 'запланировано', '', 'ВТБ РКО', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-08', 'КВ', '', 'КВ, Инвестиции', 'email', false, '', '', 'Юля', 'запланировано', '', 'Альфа Банк', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-08', 'КВ', '', 'КВ, Инвестиции', 'push', false, '', '', 'Юля', 'запланировано', '', 'Альфа Банк', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-09', 'general', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-09', 'general', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-09', 'КК', '', 'КК, ПК', 'email', false, '', '', '', '', '', 'Т-Банк Карта', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-09', 'general', '', 'клики и открытия из 1-го промо', 'email', false, '', '', 'Юля', 'запланировано', '', 'Розыгрыш Steam', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-09', 'general', '', 'клики и открытия из 1-го промо', 'push', false, '', '', 'Юля', 'запланировано', '', 'Розыгрыш Steam', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-10', 'ДК', '', 'ДК, ОСАГО, Вклады', 'push', false, '', '', 'Саша', '', '', 'Плати по миру', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-10', 'ДК', '', 'ДК, ОСАГО, Вклады', 'email', false, '', '', 'Саша', '', '', 'Плати по миру', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-10', 'general', '', 'КВ, Инвестиции', 'email', false, '', '', 'Юля', 'запланировано', '', 'Розыгрыш Ozon', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-10', 'general', '', 'КВ, Инвестиции', 'push', false, '', '', 'Юля', 'запланировано', '', 'Розыгрыш Ozon', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-10', 'general', '', 'КК, ПК, Ипотека, КПЗН', 'email', false, '', '', 'Юля', 'запланировано', '', 'Розыгрыш Ozon', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-10', 'general', '', 'КК, ПК, Ипотека, КПЗН', 'push', false, '', '', 'Юля', 'запланировано', '', 'Розыгрыш Ozon', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-11', 'КК', '', 'КК, ПК', 'push', false, '', '', '', 'запланировано', '', 'Т-Банк Карта', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-11', 'general', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-11', 'general', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-11', 'ОСАГО', '', 'ОСАГО', 'email', false, '', '', 'Таня', 'запланировано', '', 'ОСАГО от Ренессанс', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-13', 'КПЗН', '', 'КПЗН, Ипотека', 'email', false, '', '', '', '', '', 'Кредит-Клаб', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-13', 'КК', '', '', 'email', false, '', '', '', '', '', 'Уралсиб', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-13', 'general, ИС', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-13', 'Вклады', '', 'Вклады, НС, ДК, КВ, Инвестиции', 'email', false, '', '', 'Таня', 'запланировано', '', 'БЖФ', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-13', 'Вклады', '', 'Вклады, НС, ДК, КВ, Инвестиции', 'push', false, '', '', 'Таня', 'запланировано', '', 'БЖФ', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-14', 'general', '', 'ИС, ОСАГО, Каско', 'email', false, '', '', 'Юля', 'запланировано', '', 'НР: Бонус за отзыв в НРСК (Альфа страхование)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-14', 'general', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-15', 'ДК', '', 'Тотал', 'push', true, '', '', 'Саша', 'запланировано', '', 'ВТБ', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-15', 'РКО', '', 'Бизнес', 'email', false, '', '', 'Юля', 'запланировано', '', 'Инго Банк РКО', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-15', 'ОСАГО', '', 'ОСАГО', 'email', false, '', '', 'Юля', 'запланировано', '', 'Новости: Выплаты по ОСАГО выросли на 10%: что изменилось и почему это важно', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-16', 'КК', '', 'КК, ПК', 'email', false, '', '', 'Саша', 'запланировано', 'https://jira.banki.ru/browse/CRM-8742', 'Уралсиб', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-16', 'КПЗН', '', '', '', false, '', '', '', '', '', 'Норвик', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-16', 'general', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-16', 'general', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-16', 'general', '', 'Инвестиции, КВ', 'email', false, '', '', 'Юля', 'запланировано', '', 'Розыгрыш Ozon (напоминание)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-16', 'general', '', 'Инвестиции, КВ', 'push', false, '', '', 'Юля', 'запланировано', '', 'Розыгрыш Ozon (напоминание)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-17', 'КВ', '', 'КВ', 'email', false, '', '', 'Юля', 'запланировано', '', 'Новости: Порвал/испортил доллар, что с ним делать', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-17', 'ОСАГО', '', 'ОСАГО', 'email', false, '', '', 'Юля', 'запланировано', '', 'Новости: Реальная история: ездил без полиса, попал в ДТП, заплатил 700 000 ₽ и не смог списать долг', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-17', 'ДК', '', 'ДК, МФО', 'push', false, '', '', '', 'запланировано', 'https://jira.banki.ru/browse/CRM-8745', 'Плати по миру', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-18', 'ОСАГО', '', 'ОСАГО', 'email', false, '', '', 'Таня', '', '', 'ОСАГО Авто (3 письмо)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-18', 'ОСАГО', '', 'ОСАГО', 'push', false, '', '', 'Таня', '', '', 'ОСАГО Авто (3 письмо)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-18', 'ДК', '', 'ДК, ОСАГО, ПК', 'push', false, '', '', '', 'запланировано', 'https://jira.banki.ru/browse/CRM-8759', 'ПСБ 1000 Б', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-20', 'ОСАГО', '', 'ОСАГО', 'email', false, '', '', 'Юля', 'запланировано', '', 'Новости: Где найти ОСАГО дешевле: сравнение цен от 23 страховых на Банки.ру', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-20', 'general, ИС', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-20', 'general, ИС', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-20', 'РКО', '', 'Бизнес', 'email', false, '', '', 'Юля', 'запланировано', '', 'ПСБ РКО', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-20', 'Вклады', '', 'Вклады, НС, ДК, КВ, Инвестиции', 'email', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8650', 'Банк Свой', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-20', 'Вклады', '', 'Вклады, НС, ДК, КВ, Инвестиции', 'push', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8650', 'Банк Свой', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-21', 'Вклады', '', 'Тотал', 'email', true, '', '', 'Таня', '', '', '', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-21', 'Вклады', '', 'Тотал', 'push', true, '', '', 'Таня', '', '', '', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-22', 'general', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-22', 'КК', '', 'Инвестиции, Вклады, КК', 'email', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8748 
и https://jira.banki.ru/browse/CRM-8749', 'Уралсиб', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-22', 'КК', '', 'Инвестиции, Вклады, КК', 'push', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8748 
и https://jira.banki.ru/browse/CRM-8749', 'Уралсиб', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-22', 'ОСАГО', '', 'ОСАГО', 'email', false, '', '', 'Юля', 'запланировано', '', 'Новости: Где найти ОСАГО дешевле: сравнение цен от 23 страховых на Банки.ру', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-22', 'ПК', '', 'ПК', 'email', false, '', '', 'Таня', '', 'кредитование', 'Лояльность Экстра-бонус по кредиту за 1 Б', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-22', 'ПК', '', 'ПК', 'push', false, '', '', 'Таня', '', 'кредитование', 'Лояльность Экстра-бонус по кредиту за 1 Б', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-23', 'ОСАГО', '', '', 'email', false, '', '', 'Таня', 'запланировано', '', 'ОСАГО Авто (4 письмо)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-23', 'ОСАГО', '', '', 'push', false, '', '', 'Таня', 'запланировано', '', 'ОСАГО Авто (4 письмо)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-23', 'КВ', '', 'КВ', 'email', false, '', '', 'Юля', 'запланировано', '', 'Новости: Прогноз по юаню до конца лета', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-23', 'ДК', '', 'КК, ПК, МФО', 'push', false, '', '', 'Саша', 'запланировано', 'https://jira.banki.ru/browse/CRM-8746', 'Займер', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-23', 'КК', '', 'КК, МФО, ИС, КПЗН, Ипотека', 'email', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8812', 'Т-Банк', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-23', 'КК', '', 'КК, МФО, ИС, КПЗН, Ипотека', 'push', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8812', 'Т-Банк', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-24', 'Вклады', '', 'Тотал', 'email', true, '', '', 'Таня', '', '', 'ЦБ (решение)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-24', 'Вклады', '', 'Тотал', 'push', true, '', '', 'Таня', '', '', 'ЦБ (решение)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-25', 'КВ', '', 'КВ', 'email', false, '', '', 'Юля', 'запланировано', '', 'Новости: Заседание ЦБ — что будет с рублем', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-25', 'КК', '', 'ПК, ДК, КК, КПЗН, Ипотека, МФО', 'email', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8812', 'Т-Банк', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-25', 'general', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-25', 'general', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-25', 'general', '', 'Тотал', 'push', true, '', '', 'Таня', '', '', 'Мото', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-26', 'ДК', '', 'ДК, ПК', 'email', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8760', 'ПСБ 1000Б', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-26', 'КК', '', 'КК, ПК, КПЗН, Ипотека, ИС, МФО', 'push', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8812', 'Т-Банк', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'КВ', '', 'КВ', 'email', false, '', '', 'Юля', 'запланировано', '', 'Камкомбанк', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'КВ', '', 'КВ', 'push', false, '', '', 'Юля', 'запланировано', '', 'Камкомбанк', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'РКО', '', 'Бизнес', 'email', false, '', '', 'Юля', 'запланировано', '', 'РКО Ozon', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'ОСАГО', '', 'ОСАГО, ИС', 'email', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8774', 'Промо для наших клиентов / Кэшбэк начисляем быстрее', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'ОСАГО', '', 'ОСАГО, ИС', 'push', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8774', 'Промо для наших клиентов / Кэшбэк начисляем быстрее', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'Вклады', '', 'Вклады, НС, Инвестиции, ДК', 'email', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8799', 'БЖФ', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'Вклады', '', 'Вклады, НС, Инвестиции, ДК', 'push', false, '', '', 'Таня', 'запланировано', 'https://jira.banki.ru/browse/CRM-8799', 'БЖФ', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'general', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-27', 'general', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-28', 'КК', '', 'Тотал', 'email', true, '', '', '', 'запланировано', 'https://jira.banki.ru/browse/CRM-8734', 'Альфа', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-29', 'ПК', '', 'ПК', 'email', false, '', '', 'Таня', '', 'Среда, кредитование', 'Лояльность Экстра-бонус по кредиту за 1 Б', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-29', 'ПК', '', 'ПК', 'push', false, '', '', 'Таня', '', 'Среда, кредитование', 'Лояльность Экстра-бонус по кредиту за 1 Б', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-29', 'НС', '', 'Вклады, НС, Инвестиции, ДК, КВ', 'email', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8650', 'НС Морской банк с повышенной ставкой', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-29', 'НС', '', 'Вклады, НС, Инвестиции, ДК, КВ', 'push', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8650', 'НС Морской банк с повышенной ставкой', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-29', 'ОСАГО', '', 'ОСАГО', 'email', false, '', '', 'Таня', '', '', 'для ОСАГО мото', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-29', 'ОСАГО', '', 'ОСАГО', 'push', false, '', '', 'Таня', '', '', 'для ОСАГО мото', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-29', 'general', '', '', 'email', false, '', '', 'Таня', '', '', 'экстра-бонусы для новых клиентов (Лояльность)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-29', 'general', '', '', 'push', false, '', '', 'Таня', '', '', 'экстра-бонусы для новых клиентов (Лояльность)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-05', 'general', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-30', 'КПЗН', '', 'ИС, Ипотека, КПЗН', 'email', false, '', '', '', 'запланировано', 'https://jira.banki.ru/browse/CRM-8748', 'Рефинансирование', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-30', 'КВ', '', 'КВ, Инвестиции', 'email', false, '', '', 'Юля', 'запланировано', '', 'ПСБ (кликовая квота)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-30', 'КВ', '', 'КВ, Инвестиции', 'push', false, '', '', 'Юля', 'запланировано', '', 'ПСБ (кликовая квота)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-30', 'МФО', '', 'МФО', 'email', false, '', '', 'Юля', 'запланировано', '', 'Продажа двух займов', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-30', 'general', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-31', 'ОСАГО', '', 'ОСАГО', 'email', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8793', 'Обогащёнка альфа', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-31', 'ОСАГО', '', 'ОСАГО', 'push', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8793', 'Обогащёнка альфа', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-31', 'Ипотека', '', 'Ипотека', 'email', false, '', '', 'Юля', 'запланировано', '', 'ВТБ рефинансирование', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-07-31', 'КВ', '', 'КВ', 'email', false, '', '', 'Юля', 'запланировано', '', 'Новости: Прогноз евро и доллара на август', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-01', 'Кредит для бизнеса', '', 'Бизнес', 'email', false, '', '', 'Юля', 'запланировано', '', 'Займы для бизнеса Доброзайм', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-01', 'ПК', '', 'ПК', 'push', false, '', '', 'Таня', '', 'кредитование', 'Лояльность Экстра-бонус по кредиту за 1 Б', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-01', 'ПК', '', 'ПК', 'email', false, '', '', 'Таня', '', 'кредитование', 'Лояльность Экстра-бонус по кредиту за 1 Б', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-01', 'Инвестиции', '', 'Вклады, НС, Инвестиции, ДК, КВ', 'email', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8819', 'Сбер в инвестах', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-01', 'Инвестиции', '', 'Вклады, НС, Инвестиции, ДК, КВ', 'push', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8819', 'Сбер в инвестах', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-03', 'КВ', '', 'КВ', 'email', false, '', '', 'Юля', '', '', 'Конкурс "Прогноз курса"', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-03', 'КВ', '', 'КВ', 'push', false, '', '', 'Юля', '', '', 'Конкурс "Прогноз курса"', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-03', 'general', '', 'Диалог', 'push', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-03', 'general', '', 'Диалог', 'email', false, '', '', 'Юля', 'запланировано', '', 'Диалог', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-05', 'Ипотека', '', 'Ипотека', 'email', false, '', '', 'Юля', 'запланировано', '', 'Т-Банк рефинансирование', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-05', 'Ипотека', '', 'Ипотека', 'sms', false, '', '', 'Юля', 'запланировано', '', 'Т-Банк рефинансирование', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-07', 'Вклады', '', 'Вклады, НС, Инвестиции, ДК, КВ', 'email', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8831', 'Вклады. Розыгрыш денег. CRM. Анонс', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-07', 'Вклады', '', 'Вклады, НС, Инвестиции, ДК, КВ', 'push', false, '', '', 'Таня', '', 'https://jira.banki.ru/browse/CRM-8831', 'Вклады. Розыгрыш денег. CRM. Анонс', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-17', 'КВ', '', 'КВ', 'email', false, '', '', 'Юля', 'запланировано', '', 'Конкурс "Прогноз курса" (напоминание)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx'),
(DATE '2026-08-17', 'КВ', '', 'КВ', 'push', false, '', '', 'Юля', 'запланировано', '', 'Конкурс "Прогноз курса" (напоминание)', 'import:CRM-ПРОМО.xlsx', 'import:CRM-ПРОМО.xlsx');
COMMIT;
